import { Invoice, Customer, Product, ProductTemplate, AppSettings, CompanyDetails } from '../types';

export const initialCompanyDetails: CompanyDetails = {
  name: 'Your Company Name',
  address: '123 Main St, Anytown, USA',
  email: 'your@email.com',
  phone: '555-1234',
};

export const initialAppSettings: AppSettings = {
  companyDetails: initialCompanyDetails,
  defaultTaxRate: 15,
  defaultPaymentTerms: 30,
  invoicePrefix: 'INV',
  nextInvoiceNumber: 1001,
  currency: 'ZAR',
  defaultTemplate: 'modern',
  theme: 'light',
  notifications: {
    emailReminders: true,
    overdueAlerts: true,
    paymentConfirmations: true,
  },
};

export function generateMockData() {
  const customers: Customer[] = [
    {
      id: '1',
      name: 'Acme Corporation',
      email: 'billing@acme.com',
      address: '456 Oak Ave, Business City, USA',
      phone: '555-2468',
      taxId: 'TAX123456',
      createdAt: '2024-01-15T10:00:00Z',
      totalInvoices: 5,
      totalAmount: 15750.00,
    },
    {
      id: '2',
      name: 'TechStart Solutions',
      email: 'accounts@techstart.com',
      address: '789 Innovation Blvd, Tech Valley, USA',
      phone: '555-3691',
      createdAt: '2024-02-20T14:30:00Z',
      totalInvoices: 3,
      totalAmount: 8900.00,
    },
    {
      id: '3',
      name: 'Global Enterprises',
      email: 'finance@global.com',
      address: '321 Corporate Dr, Metro City, USA',
      phone: '555-7410',
      taxId: 'TAX789012',
      createdAt: '2024-03-10T09:15:00Z',
      totalInvoices: 2,
      totalAmount: 12500.00,
    },
  ];

  const products: Product[] = [
    {
      id: '1',
      name: 'Web Development',
      description: 'Custom website development services',
      unitPrice: 100,
      category: 'Development',
      taxRate: 10,
      createdAt: '2024-01-01T00:00:00Z',
    },
    {
      id: '2',
      name: 'Consulting Hours',
      description: 'Technical consulting and advisory services',
      unitPrice: 150,
      category: 'Consulting',
      taxRate: 10,
      createdAt: '2024-01-01T00:00:00Z',
    },
    {
      id: '3',
      name: 'UI/UX Design',
      description: 'User interface and experience design',
      unitPrice: 120,
      category: 'Design',
      taxRate: 10,
      createdAt: '2024-01-01T00:00:00Z',
    },
    {
      id: '4',
      name: 'Project Management',
      description: 'Project management and coordination',
      unitPrice: 80,
      category: 'Management',
      taxRate: 10,
      createdAt: '2024-01-01T00:00:00Z',
    },
  ];

  const productTemplates: ProductTemplate[] = [
    {
      id: '1',
      name: 'Pro Web Package',
      description: 'Complete web development package with design and consulting',
      items: [
        { id: '1', description: 'Web Development', quantity: 40, unitPrice: 100 },
        { id: '2', description: 'UI/UX Design', quantity: 20, unitPrice: 120 },
        { id: '3', description: 'Consulting Hours', quantity: 10, unitPrice: 150 },
      ],
      category: 'Web Development',
      totalPrice: 7900,
      createdAt: '2024-01-01T00:00:00Z',
    },
    {
      id: '2',
      name: 'Consulting Retainer',
      description: 'Monthly consulting and project management package',
      items: [
        { id: '1', description: 'Consulting Hours', quantity: 20, unitPrice: 150 },
        { id: '2', description: 'Project Management', quantity: 10, unitPrice: 80 },
      ],
      category: 'Consulting',
      totalPrice: 3800,
      createdAt: '2024-01-01T00:00:00Z',
    },
    {
      id: '3',
      name: 'Design Package',
      description: 'Complete UI/UX design with consulting',
      items: [
        { id: '1', description: 'UI/UX Design', quantity: 30, unitPrice: 120 },
        { id: '2', description: 'Consulting Hours', quantity: 5, unitPrice: 150 },
      ],
      category: 'Design',
      totalPrice: 4350,
      createdAt: '2024-01-01T00:00:00Z',
    },
    {
      id: '4',
      name: 'Enterprise Package',
      description: 'Full-service enterprise solution with all services included',
      items: [
        { id: '1', description: 'Web Development', quantity: 80, unitPrice: 100 },
        { id: '2', description: 'UI/UX Design', quantity: 40, unitPrice: 120 },
        { id: '3', description: 'Consulting Hours', quantity: 30, unitPrice: 150 },
        { id: '4', description: 'Project Management', quantity: 20, unitPrice: 80 },
      ],
      category: 'Enterprise',
      totalPrice: 18900,
      createdAt: '2024-01-01T00:00:00Z',
    },
  ];

  const invoices: Invoice[] = [
    {
      id: '1',
      invoiceNumber: 'INV-1001',
      date: '2024-12-01',
      dueDate: '2024-12-31',
      from: initialCompanyDetails,
      to: customers[0],
      customerId: '1',
      items: [
        { id: '1', description: 'Web Development', quantity: 40, unitPrice: 100 },
        { id: '2', description: 'UI/UX Design', quantity: 20, unitPrice: 120 },
      ],
      notes: 'Thank you for your business! Payment is due within 30 days.',
      paymentType: 'once-off',
      taxRate: 10,
      discountType: 'fixed',
      discountValue: 0,
      subTotal: 6400,
      taxAmount: 640,
      discountAmount: 0,
      total: 7040,
      status: 'paid',
      paymentStatus: 'paid',
      createdAt: '2024-12-01T10:00:00Z',
      updatedAt: '2024-12-15T14:30:00Z',
      sentAt: '2024-12-01T10:05:00Z',
      paidAt: '2024-12-15T14:30:00Z',
    },
    {
      id: '2',
      invoiceNumber: 'INV-1002',
      date: '2024-12-15',
      dueDate: '2025-01-14',
      from: initialCompanyDetails,
      to: customers[1],
      customerId: '2',
      items: [
        { id: '1', description: 'Consulting Hours', quantity: 25, unitPrice: 150 },
        { id: '2', description: 'Project Management', quantity: 15, unitPrice: 80 },
      ],
      notes: 'Monthly consulting retainer for December 2024.',
      paymentType: 'monthly',
      taxRate: 10,
      discountType: 'percentage',
      discountValue: 5,
      subTotal: 4950,
      taxAmount: 470.25,
      discountAmount: 247.50,
      total: 5172.75,
      status: 'sent',
      paymentStatus: 'unpaid',
      createdAt: '2024-12-15T09:00:00Z',
      updatedAt: '2024-12-15T09:05:00Z',
      sentAt: '2024-12-15T09:05:00Z',
    },
    {
      id: '3',
      invoiceNumber: 'INV-1003',
      date: '2024-11-20',
      dueDate: '2024-12-20',
      from: initialCompanyDetails,
      to: customers[2],
      customerId: '3',
      items: [
        { id: '1', description: 'Web Development', quantity: 60, unitPrice: 100 },
        { id: '2', description: 'UI/UX Design', quantity: 30, unitPrice: 120 },
      ],
      notes: 'Enterprise website development project - Phase 1.',
      paymentType: 'once-off',
      taxRate: 10,
      discountType: 'fixed',
      discountValue: 500,
      subTotal: 9600,
      taxAmount: 910,
      discountAmount: 500,
      total: 10010,
      status: 'overdue',
      paymentStatus: 'overdue',
      createdAt: '2024-11-20T11:00:00Z',
      updatedAt: '2024-12-21T10:00:00Z',
      sentAt: '2024-11-20T11:05:00Z',
    },
    {
      id: '4',
      invoiceNumber: 'INV-1004',
      date: '2025-01-02',
      dueDate: '2025-02-01',
      from: initialCompanyDetails,
      to: customers[0],
      customerId: '1',
      items: [
        { id: '1', description: 'Consulting Hours', quantity: 20, unitPrice: 150 },
      ],
      notes: 'January 2025 consulting services.',
      paymentType: 'monthly',
      taxRate: 10,
      discountType: 'fixed',
      discountValue: 0,
      subTotal: 3000,
      taxAmount: 300,
      discountAmount: 0,
      total: 3300,
      status: 'draft',
      paymentStatus: 'unpaid',
      createdAt: '2025-01-02T08:00:00Z',
      updatedAt: '2025-01-02T08:00:00Z',
    },
  ];

  return { customers, products, productTemplates, invoices };
}